# Add a concurrency group in case a tag is created, deleted, and then recreated while a release is in progress.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Only run this workflow when a tag is pushed when the tag starts with "v".
on:
  push:
    tags:
      - 'v*'

# So we can use the GitHub API to create releases with the run token.
permissions:
  contents: write

jobs:
  Release:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CriticalHPIndicator/
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.x.x

      - name: Download Dalamud Library
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d /tmp/dalamud

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build plugin in release mode
        run: dotnet build -c Release --no-restore --nologo -o ./bin/Release

      - name: Generate Checksums
        working-directory: CriticalHPIndicator/bin/Release/CriticalHPIndicator
        run: |
          sha512sum latest.zip >> checksums.sha512

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CriticalHPIndicator/bin/Release/CriticalHPIndicator/latest.zip
            CriticalHPIndicator/bin/Release/CriticalHPIndicator/checksums.sha512
          prerelease: false
          append_body: true
          body_path: .github/release-notices.md
          generate_release_notes: true
          fail_on_unmatched_files: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release Artifacts
          path: |
            CriticalHPIndicator/bin/Release/CriticalHPIndicator/latest.zip
            CriticalHPIndicator/bin/Release/CriticalHPIndicator/checksums.sha512

      - name: Update repo.json
        run: |
          cd ../

          release_version=$(echo ${{ github.ref_name }} | sed 's/^v//')
          repo_url=$(echo ${{ github.server_url }}/${{ github.repository }} | sed 's/#/\\#/g')

          sed -i repo.json -E \
              -e 's#"AssemblyVersion": "([0-9]*\.){3}[0-9]*"#"AssemblyVersion": "'"$release_version"'"#g' \
              -e 's#"TestingAssemblyVersion": "([0-9]*\.){3}[0-9]*"#"TestingAssemblyVersion": "'"$release_version"'"#' \
              -e 's#"DownloadLinkInstall": "[^"]*"#"DownloadLinkInstall": "'"$repo_url/releases/download/${{ github.ref_name }}/latest.zip"'"#g' \
              -e 's#"DownloadLinkTesting": "[^"]*"#"DownloadLinkTesting": "'"$repo_url/releases/download/${{ github.ref_name }}/latest.zip"'"#g' \
              -e 's#"DownloadLinkUpdate": "[^"]*"#"DownloadLinkUpdate": "'"$repo_url/releases/download/${{ github.ref_name }}/latest.zip"'"#g'

          git add repo.json
          git config --local user.name "github-actions [bot]"
          git config --local user.email "github-actions@users.noreply.github.com"
          git commit -m "Update repo.json for ${{ github.ref_name }}"
          
          git push origin HEAD:master
